Repository akabekobeko/npm-icon-gen, pull requests merged in 2021-12, with the labels that each got.

#136 change to sharp
  package.json
  src/lib/png.ts
Labels: enhancement

#139 chore: Added pull request to GitHub Actions
  .github/workflows/ci.yml
  examples/package.json
  src/lib/png.ts
Labels: enhancement

#140 chore: Update Node.js support to version 12 or later and update dependencies
  README.md
  package.json
Labels: enhancement, breaking change

#143 chore: Release v3.0.0
  CHANGELOG.md
  package.json
Labels: documentation
